In [1]:
pip install numpy

In [5]:
import numpy as np

# np.sort()
np1 = np.array([6,7,5,2,8,3,1,9])
print(np1)
print(np.sort(np1))

[6 7 5 2 8 3 1 9]
[1 2 3 5 6 7 8 9]


In [7]:
# Alphabetically
np2 = np.array(["ali","khizer","uzair","fahad"])
print(np2)
print(np.sort(np2))

['ali' 'khizer' 'uzair' 'fahad']
['ali' 'fahad' 'khizer' 'uzair']


In [11]:
# Boolean T/F
np3 = np.array([True,False,False,True])
print(np3)
print(np.sort(np3))

[ True False False  True]
[False False  True  True]


In [13]:
# Return a copy don't change the original
print(np1)
print(np.sort(np1))
print(np1)

[6 7 5 2 8 3 1 9]
[1 2 3 5 6 7 8 9]
[6 7 5 2 8 3 1 9]


In [15]:
# 2-D
np4 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(np4)
print(np.sort(np4))

[[1 2 3 4 5]
 [6 7 8 9 0]]
[[1 2 3 4 5]
 [0 6 7 8 9]]
