In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [21]:
import numpy as np

# Search (where function)
np1 = np.array([1,2,3,4,5,6,7,8,9,2,3])
x = np.where(np1 == 3)
print(np1)
print(x)

# To find even numbers
y = np.where(np1 % 2 == 0)
print(np1)
print(f'EVEN NUMS: {y}')

# To find odd numbers
z = np.where(np1 % 2 == 1)
print(np1)
print(f'ODD NUMS: {z}')

[1 2 3 4 5 6 7 8 9 2 3]
(array([ 2, 10], dtype=int64),)
[1 2 3 4 5 6 7 8 9 2 3]
EVEN NUMS: (array([1, 3, 5, 7, 9], dtype=int64),)
[1 2 3 4 5 6 7 8 9 2 3]
ODD NUMS: (array([ 0,  2,  4,  6,  8, 10], dtype=int64),)
