In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [41]:
# NUMPY UNIVERSAL FUNCTION

import numpy as np

np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

# Square route of each element
print(np.sqrt(np1))

# Absolute value
np2 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np.absolute(np2))

# Exponents
print(np.exp(np2))

# Min/Max
print(np.min(np1))
print(np.max(np1))

# Sign Positive or Negative
print(np.sign(np2))

# Trig Sin Cos Log
print("SIN",np.sin(np1))
print("COS",np.cos(np1))
print("TAN",np.tan(np1))


[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[3 2 1 0 1 2 3 4 5 6 7 8 9]
[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
0
9
[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]
SIN [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
COS [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
TAN [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]
