In [3]:
pip install numpy

In [60]:
# Slicing numpy arrays

import numpy as np

np1 = np.array([1,2,3,4,5,6,7,8,9])

# return 4,5,6,7,8
print(np1[3:8])

# returning something till the end of the array
print(np1[3:])

# return negative (this print the array from the last like in this array)
# ([1,2,3,4,5,6,7,8,9])
# It starts 9 as -1, 8 as -2 and so on...
print(np1[-3:-1])

# steps on the entire array
print(np1[::2]) #steps of 2
print(np1[::3]) #steps of 3

# steps
print(np1[1:5]) # 2-5
print(np1[1:5:2]) # 2-5 in steps in 2

[4 5 6 7 8]
[4 5 6 7 8 9]
[7 8]
[1 3 5 7 9]
[1 4 7]
[2 3 4 5]
[2 4]


In [56]:
# Slicing 2-d array
np2 = np.array([
    [1,2,3,4,5], 
    [6,7,8,9,10]])

# pull out a single item
print(np2[1,3])

# slice A 2d array
print(np2[0:1, 2:4]) #prints [3 4]

# slice from both rows
print(np2[0:2, 2:4])

9
[[3 4]]
[[3 4]
 [8 9]]
