In [9]:
#Lists

list1 = [1, 2, 3, 4, 5]
print (list1)

[1, 2, 3, 4, 5]


In [11]:
#installing numpy

pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [41]:
# numpy - NUMERIC PYTHON
# ndarray - ndimensional array

import numpy as np

np1 = np.array([1, 2, 3, 4, 5])
print(np1)

# print the length of array (shape function)
print(np1.shape)

# print the number within the range (arange function)
np2 = np.arange(10)
print(np2)

# print the number within the range with the steps also (2nd part of arange function)
np3 = np.arange(0, 10, 2)
print(np3)

# print the zeros (zeros function)
np4 = np.zeros(10)
print(np4)

[1 2 3 4 5]
(5,)
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
# MULTIDIMENSIONAL ARRAYS
np5 = np.zeros((2, 10))
print(np5)

# full function
np6 = np.full((10), 5)
print(np6)

# MULTIDIMENSIONAL FULL FUNCTION ARRAY
np6 = np.full((2,10), 6)
print(np6)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[5 5 5 5 5 5 5 5 5 5]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [49]:
# Convert python lists into numpy
my_list = [1, 2, 3, 4, 5]
np8 = np.array(my_list)
print(np8)

#Grabbing items in numpy array
print(np8[1])

[1 2 3 4 5]
2
