In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

# Creating 1-D Numpy array and get Shape
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [3]:
# Creating 2-D Numpy array and get Shape (rows/columns - elements)
np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [13]:
# Reshape 2-D array
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np3 = np1.reshape(3,4)
print(np3)
print(np3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [17]:
# Reshape 3-D array
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np4 = np1.reshape(2,3,2)
print(np4)
print(np4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [21]:
# Flatten to 1-D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
